name: cargo build & test

on: [push, pull_request]

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust_toolchain: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - name: Setup Rust toolchain (stable)
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust_toolchain }}
          default: true
    - uses: actions/checkout@v1
    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
